server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vuemanagement?serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis:
    type-aliases-package: com.mybatisplus.sample.mybatisplus.entity
    mapper-locations: classpath*:mapper/**.xml
    config-location: classpath:mybatis-config.xml
